##### tensors->multi dimensional array designed for mathematical   and computational efficiency

##### zero Dimensional tensor->scalar->a single number

 ##### one  dimensional tensors-> vectors,array,vectors are good example of 1d tensors


##### two dimensional tensor-> matrices,  2d grid of numbers

##### three dimensional tensors-> colored images,rgv

#####four dimensional tensors-> batches of rgb images

#####five dimensional tensors->video data

#####why tensors are useful-> mathematical  operations, representation of real world data,efficient computations

###### why tensors are used in deep learning->data storage,weights  and biases,  matrix operations,training process

## Creating tensors

In [3]:
import  torch
torch.__version__
print(torch.cuda.is_available())
print(torch.version.cuda)

True
12.6


##creating tensors

In [5]:
#using empty
torch.empty(2,3) #2,3 is the  shape
##the values are default valuesthat were in the memory location

tensor([[-2.4278e-14,  4.4655e-41, -2.4278e-14],
        [ 4.4655e-41,  0.0000e+00,  0.0000e+00]])

In [6]:
b= torch.empty(5,5)
##checking the type
print(type(b))

<class 'torch.Tensor'>


In [7]:
##zero tensors
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
##using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
##using rand
torch.rand(2,3)
#will create a tensor of 2,3 with random values
#rand will create different values everytimes

tensor([[0.1231, 0.9288, 0.7121],
        [0.9484, 0.6357, 0.7904]])

In [10]:
#so to create the same ones, we use seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#if we use the same  code again, it will produce same values/
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
##using tensor->to make custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
## other ways to create tensors

#using aranage
print(torch.arange(0,10,2)) #-> 0,10 is the range, 2 is the gap


tensor([0, 2, 4, 6, 8])


In [14]:
print(torch.linspace(0,10,10))#->0,10 is the range, 10 is the amount of evenly spaced numbers we want
#this will create 10 evenly spaced number ranged between 0-10

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [15]:
##using eye
print(torch.eye(5)) #identity matrix->diagonal 1, other 0

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [16]:
##using full->shape,the number we want the matrix to have (ie all number)
print(torch.full((2,3),4))

tensor([[4, 4, 4],
        [4, 4, 4]])


## finding tensor shapes

In [17]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)
#empty like creates a tensor of same shape, but with different values

tensor([[    136870555725200,     136870555725200,                   0],
        [                  0,        433791696896, 7310593858020254331]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

##Data types in tensors

In [22]:
a=torch.tensor([[1,2,3],[4,5,6]])

In [23]:
a.dtype

torch.int64

In [24]:
## what if we wanna specify datatype when creating tensors
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)
#although we created a tensor with float values, but since we assigned the dtype to be int,
#it changed the values  to int

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
## if we want to conver already made tensor into diffrenet data type

In [27]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
#lets change the x datatype to float
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [29]:
## Performing mathematical operation in tensors

In [30]:
torch.manual_seed(100)
x=torch.rand(2,2)
x

tensor([[0.1117, 0.8158],
        [0.2626, 0.4839]])

In [31]:
#scalar operations(operationg of tensors with single values)
print(x+2)
print(x-3)
print(x*4)
#int division
print(x*100//5)
#mod
print((x*100) %2)
#power
print(x**2)

tensor([[2.1117, 2.8158],
        [2.2626, 2.4839]])
tensor([[-2.8883, -2.1842],
        [-2.7374, -2.5161]])
tensor([[0.4467, 3.2634],
        [1.0502, 1.9355]])
tensor([[ 2., 16.],
        [ 5.,  9.]])
tensor([[1.1664, 1.5843],
        [0.2562, 0.3878]])
tensor([[0.0125, 0.6656],
        [0.0689, 0.2341]])


## Element  wise operations on multiple tensors

In [33]:

a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.6765, 0.7539, 0.2627],
        [0.0428, 0.2080, 0.1180]])
tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])


In [34]:
##add
a+b ## does item wise addition

tensor([[0.7982, 1.4895, 0.9745],
        [0.8304, 0.6263, 1.0195]])

In [35]:
##sub
a-b ## does item wise sub

tensor([[ 0.5548,  0.0183, -0.4491],
        [-0.7447, -0.2103, -0.7834]])

In [36]:
##mul
a*b ## does item wise mul

tensor([[0.0823, 0.5546, 0.1870],
        [0.0337, 0.0870, 0.1064]])

In [37]:
##div
a/b ## does item wise div

tensor([[5.5590, 1.0249, 0.3691],
        [0.0544, 0.4973, 0.1309]])

In [38]:
## Other operations

In [39]:
# absolute value
c=torch.tensor([-1,-2,-3])
torch.abs(c)

tensor([1, 2, 3])

In [40]:
##negative
c=torch.tensor([-1,-2,-3])
torch.neg(c)

tensor([1, 2, 3])

In [41]:
##roud
d=torch.tensor([1.1,2.2,3.3])
torch.round(d)

tensor([1., 2., 3.])

In [42]:
#ceil
e=torch.tensor([1.2,5.6,7.8])
torch.ceil(e)

tensor([2., 6., 8.])

In [43]:
#floor
e=torch.tensor([1.2,5.6,7.8])
torch.floor(e)

tensor([1., 5., 7.])

In [44]:
##clamp -> makes every numbers into a certain range
#floor
e=torch.tensor([1.2,5.6,7.8,8.5])
torch.clamp(e,min=2,max=5)

tensor([2., 5., 5., 5.])

## Reduction operations->bringing entire tensor into a single number

In [46]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[1., 0., 4.],
        [3., 8., 7.]])

In [47]:

#sum
torch.sum(e)

tensor(23.)

In [48]:







##sum along columns
torch.sum(e,dim=0)

tensor([ 4.,  8., 11.])

In [49]:
##sum along rows
torch.sum(e,dim=1)

tensor([ 5., 18.])

In [50]:
##mean
torch.mean(e,dtype=torch.float32)
#torch.mean only works on float data

tensor(3.8333)

In [51]:
#mean along col
torch.mean(e,dim=0)

tensor([2.0000, 4.0000, 5.5000])

In [52]:

#mean along row
torch.mean(e,dim=1)

tensor([1.6667, 6.0000])

In [53]:
##median
torch.median(e)

tensor(3.)

In [54]:
##max  and min
torch.max(e)

tensor(8.)

In [55]:
torch.min(e)


tensor(0.)

In [56]:
##product
torch.prod(e)

tensor(0.)

In [57]:
#st deviation
torch.std(e)


tensor(3.1885)

In [58]:
#variaance
torch.var(e)

tensor(10.1667)

In [59]:
## argmax->tells the position of the largest item
torch.argmax(e)

tensor(4)

In [60]:
## argmin->tells the position of the minimum item
torch.argmin(e)

tensor(1)

## Matrix operation

In [61]:
a=torch.randint(size=(2,3),low=0,high=10)
b=torch.randint(size=(3,2),low=0,high=10)
print(a)
print(b)

tensor([[4, 6, 0],
        [1, 9, 9]])
tensor([[8, 0],
        [7, 0],
        [0, 9]])


In [62]:
##matrix mul
torch.matmul(a,b)

tensor([[74,  0],
        [71, 81]])

In [63]:
#dot product
vector1= torch.tensor([1,2])
vector2=torch.tensor([3,4])

torch.dot(vector1,vector2)

tensor(11)

In [64]:
##transpose
print(a)
torch.transpose(a,0,1)

tensor([[4, 6, 0],
        [1, 9, 9]])


tensor([[4, 1],
        [6, 9],
        [0, 9]])

In [65]:
#determinant
g=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(g)
torch.det(g)

tensor([[5., 7., 3.],
        [9., 4., 0.],
        [5., 7., 5.]])


tensor(-86.0000)

In [66]:
#inverse
torch.inverse(g)

tensor([[-2.3256e-01,  1.6279e-01,  1.3953e-01],
        [ 5.2326e-01, -1.1628e-01, -3.1395e-01],
        [-5.0000e-01,  9.7031e-09,  5.0000e-01]])

## Comparision Operations


In [68]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[9, 9, 7],
        [5, 9, 8]])
tensor([[9, 7, 9],
        [2, 6, 7]])


In [69]:
#comparision
#greater than
i>j #compres 1 with 6->true, 2 with 6->false ,7 with 8 ->false..and so on
#item wise

tensor([[False,  True, False],
        [ True,  True,  True]])

In [70]:
#less than
i<j

tensor([[False, False,  True],
        [False, False, False]])

In [71]:
#equal to
i==j

tensor([[ True, False, False],
        [False, False, False]])

In [72]:
#not equal to
i!=j

tensor([[False,  True,  True],
        [ True,  True,  True]])

In [73]:
#greter  than equal to
i>=j

tensor([[ True,  True, False],
        [ True,  True,  True]])

In [74]:
#less  than equal to
i<=j

tensor([[ True, False,  True],
        [False, False, False]])

## special functions

In [75]:
k=torch.randint(size=(2,3),low=0,high=10)
print(k)

tensor([[7, 8, 3],
        [6, 1, 5]])


In [76]:
#log
torch.log(k)

tensor([[1.9459, 2.0794, 1.0986],
        [1.7918, 0.0000, 1.6094]])

In [77]:
#exponents
torch.exp(k)


tensor([[1.0966e+03, 2.9810e+03, 2.0086e+01],
        [4.0343e+02, 2.7183e+00, 1.4841e+02]])

In [78]:
#square root
torch.sqrt(k)

tensor([[2.6458, 2.8284, 1.7321],
        [2.4495, 1.0000, 2.2361]])

In [79]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9997, 0.9526],
        [0.9975, 0.7311, 0.9933]])

In [80]:
#softmax
torch.softmax(k.to(torch.float32), dim=0)


tensor([[7.3106e-01, 9.9909e-01, 1.1920e-01],
        [2.6894e-01, 9.1105e-04, 8.8080e-01]])

## Inplace operations

In [81]:
#in-place operation modifies the tensor itself instead of creating a new one.
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.6726, 0.5740, 0.9233],
        [0.9178, 0.7590, 0.7775]])
tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])


In [82]:
m.add_(n)

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [83]:
m #it modified m instead of creating a new tensor, that would occupy the space, tosolve  this problem we used inplace operations

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [84]:
n

tensor([[0.6179, 0.3379, 0.2170],
        [0.9454, 0.7116, 0.1157]])

In [85]:
torch.relu(m) #this will craete a completely new tensor

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [86]:
m.relu_()#this wll modfy exisiting ones

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

In [87]:
m

tensor([[1.2905, 0.9118, 1.1403],
        [1.8632, 1.4706, 0.8933]])

## Copying a tensor

In [88]:
a=torch.rand(2,3)
a

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [89]:
b=a

In [90]:
a

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [91]:
b

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])

In [92]:
#theproblem with  this type of copying is  that changes get reflected,if we change a it will change b too..we dont want that

In [93]:
b=a.clone()##thisisbetter

## Tensors operation in GPU

In [94]:
torch.cuda.is_available()

True

In [95]:
device= torch.device('cuda')

In [96]:
#creatinganew tensor ingpu
torch.rand(2,3,device=device)#his tensor inmadein gpu

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [97]:
#moving an existing tensor in  gpu
a=torch.rand(2,3)
a
#this is made in cpu

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [98]:
b=a.to(device)

In [99]:
b+5

tensor([[5.4920, 5.0748, 5.9605],
        [5.3271, 5.0103, 5.9516]], device='cuda:0')

In [100]:
#this is performed in gpu

## Reshaping in tensors


In [101]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [102]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [104]:
##Permute
b=torch.rand(2,3,4)
b

tensor([[[0.2855, 0.2324, 0.9141, 0.7668],
         [0.1659, 0.4393, 0.2243, 0.8935],
         [0.0497, 0.1780, 0.3011, 0.1893]],

        [[0.9186, 0.2131, 0.3957, 0.6017],
         [0.4234, 0.5224, 0.4175, 0.0340],
         [0.9157, 0.3079, 0.6269, 0.8277]]])

In [105]:
b.permute(2,0,1)

tensor([[[0.2855, 0.1659, 0.0497],
         [0.9186, 0.4234, 0.9157]],

        [[0.2324, 0.4393, 0.1780],
         [0.2131, 0.5224, 0.3079]],

        [[0.9141, 0.2243, 0.3011],
         [0.3957, 0.4175, 0.6269]],

        [[0.7668, 0.8935, 0.1893],
         [0.6017, 0.0340, 0.8277]]])