# 🧠 PyTorch `nn` Module (Quick Notes)

## What is `torch.nn`?
- Core module for building neural networks
- Provides layers, activations, losses, and containers

## Main Components
- `nn.Module` → Base class for all models
- `nn.Linear` → Fully connected layer
- `nn.Conv2d` → Convolution layer
- `nn.LSTM`, `nn.GRU` → Recurrent layers
- `nn.Embedding` → Word embeddings

## Activation Functions
- `nn.ReLU`
- `nn.Sigmoid`
- `nn.Tanh`
- `nn.Softmax`

## Loss Functions
- `nn.MSELoss`
- `nn.CrossEntropyLoss`
- `nn.BCELoss`

## Model Flow
- Define layers in `__init__`
- Define computation in `forward()`
- PyTorch handles backprop automatically

## Common Utilities
- `nn.Sequential` → Stack layers easily
- `model.parameters()` → Get trainable params
- `model.train()` / `model.eval()`

## Typical Usage
- Forward pass → Loss → Backward → Optimizer step


##### We will create a neural network that takes 5 inputs and produces a output(binary classification )


In [7]:
#### Create a model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,input_features):
    super().__init__()
    self.linear= nn.Linear(input_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    output=self.linear(features)
    output=self.sigmoid(output)
    return output


In [8]:
# Create a simple dataset
features = torch.rand(10, 5)  # 10 rows, 5 columns

# Create the model
model = Model(features.shape[1])

# Call the model
output = model(features)
print(output)

tensor([[0.2964],
        [0.3459],
        [0.3438],
        [0.2781],
        [0.3871],
        [0.2952],
        [0.3483],
        [0.3958],
        [0.4228],
        [0.3660]], grad_fn=<SigmoidBackward0>)


In [9]:
#### showing weights
model.linear.weight

Parameter containing:
tensor([[-0.4454, -0.3212, -0.2659, -0.1100,  0.0665]], requires_grad=True)

In [10]:
#### showing bias
model.linear.bias

Parameter containing:
tensor([-0.1669], requires_grad=True)

In [13]:
!pip install torchinfo


In [14]:
####Visualizing the nn
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#### Let's build a bigger neural network
- 5 input features
- 1 hidden layer with 3 nodes
- 1 output node
for hidden we will use relu and for output we use sigmoid


In [15]:
class Model(nn.Module):
  def __init__(self,input_features):
    super().__init__()
    self.linear1=nn.Linear(input_features,3)
    self.relu=nn.ReLU(3)
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,df):
    output=self.linear1(df)
    output=self.relu(output)
    output=self.linear2(output)
    output=self.sigmoid(output)
    return output

In [16]:
df=torch.rand(10,5)
model=Model(df.shape[1])
output=model(df)
print(output)

tensor([[0.3943],
        [0.4113],
        [0.3974],
        [0.3801],
        [0.3977],
        [0.4083],
        [0.4329],
        [0.3960],
        [0.3974],
        [0.4064]], grad_fn=<SigmoidBackward0>)


In [17]:
####Visualizing the nn
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

##### the above is one way to do it, to do it even better, we can use containers like squential/


In [19]:
class Model(nn.Module):

  def __init__(self,input_features):
    super().__init__()
    self.neural_network=nn.Sequential(
    nn.Linear(input_features,3),
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )

  def forward(self,df):
    output=self.neural_network(df)
    return output

In [20]:
df=torch.rand(10,5)
model=Model(df.shape[1])
output=model(df)
print(output)

tensor([[0.6407],
        [0.6179],
        [0.6053],
        [0.6182],
        [0.6266],
        [0.6488],
        [0.6334],
        [0.6316],
        [0.5977],
        [0.6081]], grad_fn=<SigmoidBackward0>)


In [21]:
####Visualizing the nn
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [22]:
#### this is how we use nn module with sequential container